version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/coc-deploy
    overwrite: yes
permissions:
  - object: /usr/share/nginx/html/coc-deploy
    owner: root
    group: root
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
