module.exports = {
  content: ["./components/**/*.tsx", "./pages/**/*.tsx", "./layouts/**/*.tsx"],
  theme: {
    colors: {
      white: "#ffffff",
      black: "#000000",
      pink: "#d668a5",
      lightgray: "#383838",
      lightgray2: "#a3a3a3",
      layout: "#171A21",
      title: "#F8F9FB",
      input: "#3D3D3D",
      label1: "#2f2c63",
      border1: "#3e365e",
      border2: "#69759d",
      border3: "#72639c",
      background1: "#8a94ad",
      background2: "#6b789a",
      background3: "#4e4c78",
      background4: "#e8e8e0",
      background5: "#606a8d",
      button1: "#a49d96",
      button2: "#847b72",
      button3: "#cbc9bc",
      button4: "#bab8a9",
      maxLevel: "#e8b55f",
    },
    borderWidth: {
      "0": "0",
      "1": "1px",
      "2": "2px",
      "3": "3px",
    },
    typography: (theme) => ({}),
    extend: {
      backgroundImage: {
        homeBackground: "url('/assets/images/background/homeBackground.webp')",
        headerLogo: "url('/assets/images/logo/headerLogo.webp')",
        titleLogo: "url('/assets/images/logo/titleLogo.webp')",
      },
      flexGrow: {
        "0": 0,
        "0.2": 0.2,
        "0.3": 0.3,
        "0.4": 0.4,
        "0.5": 0.5,
        "0.6": 0.6,
        "0.7": 0.7,
        "0.8": 0.8,
        "0.9": 0.9,
        "1": 1,
        "2": 2,
      },
      fontFamily: {
        supercell: ["SUPERCELL", "sans-serif"],
        hoonjeonggeulbookR: ["HOONJEONGGEULBOOKR", "sans-serif"],
      },
    },
  },
  variants: {},
  plugins: [require("@tailwindcss/typography")],
};
