import {
  BabyDragonBuilder,
  BetaMinion,
  Bomber,
  BoxerGiant,
  CannonCart,
  DropShip,
  HogGlider,
  NightWitch,
  RagedBarbarian,
  SneakyArcher,
  SuperPEKKA,
  Archer,
  BabyDragon,
  Ballon,
  Barbarian,
  BattleBlimp,
  Bowler,
  Dragon,
  DragonRider,
  ElectroDragon,
  FlameFlinger,
  Giant,
  Goblin,
  Golem,
  Headhunter,
  Healer,
  HogRider,
  IceGolem,
  LavaHound,
  LogLauncher,
  Miner,
  Minion,
  PEKKA,
  SiegeBarracks,
  StoneSlammer,
  Valkyrie,
  WallBreaker,
  WallWrecker,
  Witch,
  Wizard,
  Yeti,
  ArcherQueen,
  BarbarianKing,
  BattleMachine,
  GrandWarden,
  RoyalChampion,
  ElectroOwl,
  LASSI,
  MightyYak,
  Unicorn,
  IceHound,
  InfernoDragon,
  RocketBalloon,
  SneakyGoblin,
  SuperArcher,
  SuperBarbarian,
  SuperBowler,
  SuperDragon,
  SuperGiant,
  SuperMinion,
  SuperValkyrie,
  SuperWallBreaker,
  SuperWitch,
  SuperWizard,
} from "public/assets/images/troops";

const troops = {
  home: {
    Barbarian,
    Archer,
    Goblin,
    Giant,
    "Wall Breaker": WallBreaker,
    Ballon,
    Wizard,
    Healer,
    Dragon,
    "P.E.K.A.A": PEKKA,
    Minion,
    "Hog Rider": HogRider,
    Valkyrie,
    Golem,
    Witch,
    "Lava Hound": LavaHound,
    Bowler,
    "Baby Dragon": BabyDragon,
    Miner,
    Yeti,
    IceGolem,
    "Electro Dragon": ElectroDragon,
    Headhunter,
    DragonRider,
  },
  siege: {
    "Wall Wrecker": WallWrecker,
    "Battle Blimp": BattleBlimp,
    "Stone Slammer": StoneSlammer,
    "Flame Flinger": FlameFlinger,
    "Log Launcher": LogLauncher,
    "Siege Barracks": SiegeBarracks,
  },
  super: {
    "Super barbarian": SuperBarbarian,
    "Super Archer": SuperArcher,
    "Super Wall Breaker": SuperWallBreaker,
    "Super Giant": SuperGiant,
    "Sneaky Goblin": SneakyGoblin,
    "Rocket Balloon": RocketBalloon,
    "Inferno Dragon": InfernoDragon,
    "Super Valkyrie": SuperValkyrie,
    "Super Witch": SuperWitch,
    "Ice Hound": IceHound,
    "Super Bowler": SuperBowler,
    "Super Dragon": SuperDragon,
    "Super Wizard": SuperWizard,
    "Super Minion": SuperMinion,
  },
  builderBase: {
    "Raged Barbarian": RagedBarbarian,
    "Sneaky Archer": SneakyArcher,
    "Beta Minion": BetaMinion,
    "Boxer Giant": BoxerGiant,
    Bomber,
    "Super P.E.K.K.A": SuperPEKKA,
    "Cannon Cart": CannonCart,
    "Drop Ship": DropShip,
    "Baby Dragon": BabyDragonBuilder,
    "Night Witch": NightWitch,
    "Hog Glider": HogGlider,
  },
  heroes: {
    "Archer Queen": ArcherQueen,
    "Barbarian King": BarbarianKing,
    "Battle Machine": BattleMachine,
    "Grand Warden": GrandWarden,
    "Royal Champion": RoyalChampion,
  },
  pets: {
    ElectroOwl,
    LASSI,
    MightyYak,
    Unicorn,
  },
};

export default troops;
